[package]
name = "rustdesk_harmony_bridge"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"
publish = false

[lib]
crate-type = ["staticlib"]

[dependencies]
rustdesk_core = { package = "rustdesk", path = "../rustdesk-master", default-features = false }

[patch."https://github.com/rustdesk-org/machine-uid"]
machine-uid = { path = "../patches/machine-uid/381ff57" }

[patch."https://github.com/rustdesk-org/rdev"]
rdev = { git = "https://github.com/liyan-lucky/rdev", rev = "cf6fe32254d0e31d67f819d61f996372243b99e5" }

