// Auto-generated FFI bindings for libsodium
// This file is generated by build.rs - do not edit manually

#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case)]
#![allow(dead_code, unused_imports)]

extern "C" {
    // Version
    pub fn sodium_version_string() -> *const libc::c_char;
    pub fn sodium_library_version_string() -> *const libc::c_char;
    pub fn sodium_library_minimal() -> libc::c_int;

    // Core
    pub fn sodium_init() -> libc::c_int;
    pub fn sodium_pad(padlen: *mut libc::u8, buf: *const libc::u8, buflen: usize, maxbuflen: usize) -> libc::c_int;
    pub fn sodium_unpad(unpaddedbuf: *mut libc::u8, unpaddedbullen: *mut usize, paddedbuf: *const libc::u8, paddedbulen: usize, padlen: usize) -> libc::c_int;

    // Random
    pub fn randombytes_buf(buf: *mut libc::c_void, len: usize) -> ();
    pub fn randombytes_buf_deterministic(buf: *mut libc::c_void, len: usize, state: *const crypto_state) -> ();
    pub fn randombytes_random() -> libc::c_uint;
    pub fn randombytes_stir() -> ();
    pub fn randombytes_set_implementation(implementation: *const randombytes_implementation) -> libc::c_int;
    pub fn randombytes_align_internal_random() -> ();

    // Secretbox
    pub fn crypto_secretbox_keybytes() -> usize;
    pub fn crypto_secretbox_noncebytes() -> usize;
    pub fn crypto_secretbox_macbytes() -> usize;
    pub fn crypto_secretbox_easy(c: *mut libc::c_uchar, m: *const libc::c_uchar, mlen: usize, n: *const libc::c_uchar, k: *const libc::c_uchar) -> libc::c_int;
    pub fn crypto_secretbox_open_easy(m: *mut libc::c_uchar, c: *const libc::c_uchar, clen: usize, n: *const libc::c_uchar, k: *const libc::c_uchar) -> libc::c_int;
    pub fn crypto_secretbox_detached(c: *mut libc::c_uchar, mac: *mut libc::c_uchar, m: *const libc::c_uchar, mlen: usize, n: *const libc::c_uchar, k: *const libc::c_uchar) -> libc::c_int;
    pub fn crypto_secretbox_open_detached(m: *mut libc::c_uchar, c: *const libc::c_uchar, mac: *const libc::c_uchar, clen: usize, n: *const libc::c_uchar, k: *const libc::c_uchar) -> libc::c_int;

    // Box
    pub fn crypto_box_keypair(pk: *mut libc::c_uchar, sk: *mut libc::c_uchar) -> libc::c_int;
    pub fn crypto_box_seal(c: *mut libc::c_uchar, m: *const libc::c_uchar, mlen: usize, pk: *const libc::c_uchar) -> libc::c_int;
    pub fn crypto_box_seal_open(m: *mut libc::c_uchar, c: *const libc::c_uchar, clen: usize, pk: *const libc::c_uchar, sk: *const libc::c_uchar) -> libc::c_int;

    // Sign
    pub fn crypto_sign_seed_keypair(pk: *mut libc::c_uchar, sk: *mut libc::c_uchar, seed: *const libc::c_uchar) -> libc::c_int;
    pub fn crypto_sign_keypair(pk: *mut libc::c_uchar, sk: *mut libc::c_uchar) -> libc::c_int;
    pub fn crypto_sign_statebytes() -> usize;
    pub fn crypto_sign(pk: *mut libc::c_uchar, siglen: *mut usize, m: *const libc::c_uchar, mlen: usize, sk: *const libc::c_uchar) -> libc::c_int;
    pub fn crypto_sign_open(m: *mut libc::c_uchar, mlen: *mut usize, sm: *const libc::c_uchar, smlen: usize, pk: *const libc::c_uchar) -> libc::c_int;
    pub fn crypto_sign_detached(sig: *mut libc::c_uchar, siglen: *mut usize, m: *const libc::c_uchar, mlen: usize, sk: *const libc::c_uchar) -> libc::c_int;
    pub fn crypto_sign_verify(sig: *const libc::c_uchar, siglen: usize, m: *const libc::c_uchar, mlen: usize, pk: *const libc::c_uchar) -> libc::c_int;

    // Auth
    pub fn crypto_auth_keybytes() -> usize;
    pub fn crypto_auth_bytes() -> usize;
    pub fn crypto_auth(out: *mut libc::c_uchar, in_: *const libc::c_uchar, inlen: usize, k: *const libc::c_uchar) -> libc::c_int;
    pub fn crypto_auth_verify(h: *const libc::c_uchar, in_: *const libc::c_uchar, inlen: usize, k: *const libc::c_uchar) -> libc::c_int;

    // Hash
    pub fn crypto_hash_statebytes() -> usize;
    pub fn crypto_hash(out: *mut libc::c_uchar, in_: *const libc::c_uchar, inlen: usize) -> libc::c_int;

    // Key exchange
    pub fn crypto_box_sessionkeybytes() -> usize;
    pub fn crypto_box_publickeybytes() -> usize;
    pub fn crypto_box_secretkeybytes() -> usize;
    pub fn crypto_box_noncebytes() -> usize;
    pub fn crypto_box_macbytes() -> usize;
    pub fn crypto_box_precomputationbytes() -> usize;
    pub fn crypto_box_beforenm(k: *mut libc::c_uchar, pk: *const libc::c_uchar, sk: *const libc::c_uchar) -> libc::c_int;
    pub fn crypto_box_afternm(c: *mut libc::c_uchar, m: *const libc::c_uchar, mlen: usize, n: *const libc::c_uchar, k: *const libc::c_uchar) -> libc::c_int;
    pub fn crypto_box_open_afternm(m: *mut libc::c_uchar, c: *const libc::c_uchar, clen: usize, n: *const libc::c_uchar, k: *const libc::c_uchar) -> libc::c_int;
    pub fn crypto_box_detached(c: *mut libc::c_uchar, mac: *mut libc::c_uchar, m: *const libc::c_uchar, mlen: usize, n: *const libc::c_uchar, k: *const libc::c_uchar) -> libc::c_int;
    pub fn crypto_box_open_detached(m: *mut libc::c_uchar, c: *const libc::c_uchar, mac: *const libc::c_uchar, clen: usize, n: *const libc::c_uchar, k: *const libc::c_uchar) -> libc::c_int;
    pub fn crypto_box_curve25519xsalsa20poly1305_sessionkeypair(pk: *mut libc::c_uchar, sk: *mut libc::c_uchar, msg: *const libc::c_uchar, n: *const libc::c_uchar) -> libc::c_int;
    pub fn crypto_box_curve25519xsalsa20poly1305_sessionkeypair_from_ck(pk: *mut libc::c_uchar, sk: *mut libc::c_uchar, msg: *const libc::c_uchar, n: *const libc::c_uchar, ck: *const libc::c_uchar) -> libc::c_int;
    pub fn crypto_box_curve25519xsalsa20poly1305_sessionkeys_from_ck(pk: *mut libc::c_uchar, sk: *mut libc::c_uchar, msg: *const libc::c_uchar, n: *const libc::c_uchar, ck: *const libc::c_uchar) -> libc::c_int;
    pub fn crypto_box_curve25519xsalsa20poly1305_sessionkeys_from_ck_and_pk(pk: *mut libc::c_uchar, sk: *mut libc::c_uchar, msg: *const libc::c_uchar, n: *const libc::c_uchar, ck: *const libc::c_uchar, pk: *const libc::c_uchar) -> libc::c_int;
    pub fn crypto_box_curve25519xsalsa20poly1305_sessionkeys_from_ck_and_pk_and_sk(pk: *mut libc::c_uchar, sk: *mut libc::c_uchar, msg: *const libc::c_uchar, n: *const libc::c_uchar, ck: *const libc::c_uchar, pk: *const libc::c_uchar, sk: *const libc::c_uchar) -> libc::c_int;

    // Pwhash
    pub fn crypto_pwhash_alg_default() -> libc::c_int;
    pub fn crypto_pwhash_alg_argon2i13() -> libc::c_int;
    pub fn crypto_pwhash_alg_argon2id13() -> libc::c_int;
    pub fn crypto_pwhash_alg_min() -> libc::c_int;
    pub fn crypto_pwhash_alg_max() -> libc::c_int;
    pub fn crypto_pwhash_bytes_min() -> usize;
    pub fn crypto_pwhash_bytes_max() -> usize;
    pub fn crypto_pwhash_passwd_min() -> usize;
    pub fn crypto_pwhash_passwd_max() -> usize;
    pub fn crypto_pwhash_salt_min() -> usize;
    pub fn crypto_pwhash_salt_max() -> usize;
    pub fn crypto_pwhash_opslimit_min() -> usize;
    pub fn crypto_pwhash_opslimit_max() -> usize;
    pub fn crypto_pwhash_memlimit_min() -> usize;
    pub fn crypto_pwhash_memlimit_max() -> usize;
    pub fn crypto_pwhash_opslimit_interactive() -> usize;
    pub fn crypto_pwhash_memlimit_interactive() -> usize;
    pub fn crypto_pwhash_opslimit_sensitive() -> usize;
    pub fn crypto_pwhash_memlimit_sensitive() -> usize;
    pub fn crypto_pwhash(out: *mut libc::c_uchar, outlen: usize, passwd: *const libc::c_uchar, passwdlen: usize, salt: *const libc::c_uchar, opslimit: usize, memlimit: usize, alg: libc::c_int) -> libc::c_int;
    pub fn crypto_pwhash_str(out: *mut libc::c_uchar, passwd: *const libc::c_uchar, passwdlen: usize, opslimit: usize, memlimit: usize) -> libc::c_int;
    pub fn crypto_pwhash_str_verify(str_: *const libc::c_uchar, passwd: *const libc::c_uchar, passwdlen: usize) -> libc::c_int;
    pub fn crypto_pwhash_str_needs_rehash(str_: *const libc::c_uchar, opslimit: usize, memlimit: usize) -> libc::c_int;

    // Verify
    pub fn crypto_verify_16(a: *const libc::c_uchar, b: *const libc::c_uchar) -> libc::c_int;
    pub fn crypto_verify_32(a: *const libc::c_uchar, b: *const libc::c_uchar) -> libc::c_int;
    pub fn crypto_verify_64(a: *const libc::c_uchar, b: *const libc::c_uchar) -> libc::c_int;
}

// Constants
pub const crypto_secretbox_KEYBYTES: usize = 32;
pub const crypto_secretbox_NONCEBYTES: usize = 24;
pub const crypto_secretbox_MACBYTES: usize = 16;
pub const crypto_box_PUBLICKEYBYTES: usize = 32;
pub const crypto_box_SECRETKEYBYTES: usize = 32;
pub const crypto_box_NONCEBYTES: usize = 24;
pub const crypto_box_MACBYTES: usize = 16;
pub const crypto_box_SEALBYTES: usize = 24 + 32;
pub const crypto_sign_SEEDBYTES: usize = 32;
pub const crypto_sign_PUBLICKEYBYTES: usize = 32;
pub const crypto_sign_SECRETKEYBYTES: usize = 64;
pub const crypto_sign_BYTES: usize = 64;
pub const crypto_auth_KEYBYTES: usize = 32;
pub const crypto_auth_BYTES: usize = 32;
pub const crypto_hash_BYTES: usize = 64;
pub const crypto_scalarmult_BYTES: usize = 32;
pub const crypto_scalarmult_SCALARBYTES: usize = 32;
pub const crypto_generichash_MIN_KEYBYTES: usize = 16;
pub const crypto_generichash_MAX_KEYBYTES: usize = 64;
pub const crypto_generichash_BYTES_MIN: usize = 16;
pub const crypto_generichash_BYTES_MAX: usize = 64;
pub const crypto_generichash_BYTES: usize = 32;
pub const crypto_generichash_PERSONALBYTES: usize = 16;
pub const crypto_onetimeauth_BYTES: usize = 16;
pub const crypto_onetimeauth_KEYBYTES: usize = 32;
pub const crypto_stream_KEYBYTES: usize = 32;
pub const crypto_stream_NONCEBYTES: usize = 24;
pub const crypto_kx_SESSIONKEYBYTES: usize = 32;
pub const crypto_kx_CLIENTPUBLICKEYBYTES: usize = 32;
pub const crypto_kx_CLIENTSECRETKEYBYTES: usize = 32;
pub const crypto_kx_SERVERPUBLICKEYBYTES: usize = 32;
pub const crypto_kx_SERVERSECRETKEYBYTES: usize = 32;

