// Minimal lib.rs for libsodium-sys patch
// The actual FFI bindings are generated by build.rs when building from source.
// When using SODIUM_LIB_DIR, this file is not strictly needed but cargo requires it.
